from pydantic import BaseModel, EmailStr, Field, field_serializer
from typing import List, Dict, Any, Optional
import uuid

#v1 schemas (some still required and some not)
class SignupRequest(BaseModel):
    username: str
    email: EmailStr
    password: str

class LoginRequest(BaseModel):
    username: str
    password: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"

class DocumentMetadata(BaseModel):
    """
    A flexible container for metadata associated with a document chunk.
    This structure is used internally and can be part of API responses.
    """
    source_file: Optional[str] = None
    source_type: Optional[str] = Field(None, description="The type of the source file, e.g., 'pdf', 'csv', 'txt'")
    page_count: Optional[int] = None
    row_count: Optional[int] = None
    column_headers: Optional[List[str]] = None
    chunk_number: Optional[int] = None


class DocumentUploadResponse(BaseModel):
    """
    The response sent back to the client after a successful file upload and processing.
    """
    message: str = Field(..., description="A summary of the processing outcome.")
    filename: str = Field(..., description="The name of the file that was processed.")
    doc_id: str = Field(..., description="The unique document ID assigned to the processed file.")
    chunks_added: int = Field(..., description="The number of chunks the document was split into and added to the database.")


class DocumentInfo(BaseModel):
    """
    A summary of a single document present in the system, used for listing documents.
    """
    doc_id: str = Field(..., description="The unique document ID.")
    filename: Optional[str] = Field(None, description="The original filename of the document.")
    source_type: Optional[str] = Field(None, description="The type of the source file, e.g., 'pdf', 'csv'.")


class ListDocumentsResponse(BaseModel):
    """
    The response containing a list of all documents currently in the vector store.
    """
    total_documents: int = Field(..., description="The total number of unique documents in the system.")
    documents: List[DocumentInfo] = Field(..., description="A list containing summary information for each document.")


class QueryRequest(BaseModel):
    """
    The request model for a user's query. It includes the question and any
    parameters for the RAG process.
    """
    query_text: str = Field(..., min_length=1, description="The natural language query from the user.")
    n_results: int = Field(default=5, ge=1, le=50, description="The number of relevant document chunks to retrieve for context.")


class QueryResponse(BaseModel):
    """
    The simplified response model for a user query. It returns the original
    query and a single, synthesized answer string.
    """
    original_query: str = Field(..., description="The original query text submitted by the user.")
    synthesized_answer: str = Field(..., description="The final, consolidated answer generated by the AI.")


class StatusResponse(BaseModel):
    """
    A generic response model for endpoints that return a simple status message,
    often used for administrative tasks.
    """
    status: str
    message: Optional[str] = None

# schemas for v2
class InteractionRequest(BaseModel):
    """
    The request model for the unified interaction endpoint.
    """
    interaction_id: Optional[uuid.UUID] = Field(None, description="ID of a chat session to continue, or None for a new chat.")
    query_text: str = Field(..., min_length=1, description="the user query")

class InteractionResponse(BaseModel):
    """
    The response from the unified interaction endpoint, containing the AI's
    answer and the ID of the interaction session.
    """
    interaction_id: uuid.UUID = Field(..., description="The ID of the chat session.")
    synthesized_answer: str = Field(..., description="AI's response to the user's query.")

class ChatMessage(BaseModel):
    """
    Represents a single message within a chat history.
    """
    id : uuid.UUID
    role: str
    content: str
    timestamp: Optional[str] = None

    class Config:
        from_attributes = True 

class InteractionInfo(BaseModel):
    """
    A summary of a single interaction, used for listing all past chats.
    """
    id: uuid.UUID
    title: str
    created_at: str
    class Config:
        from_attributes = True

class InteractionHistory(InteractionInfo):
    """

    Represents the full details of a single interaction, including all messages.
    """
    messages: List[ChatMessage] = []

    class Config:
        from_attributes = True